### ISSUE TITLE
Agency GUI visual design research

### ISSUE THREAD

**Issue by leahbannon** [usdoj/foia.gov#34] opened 2017-08-01 23:02 UTC
- [x] review 90% list
- [x] review web design standards in order to make recommendation: can we use them?
- [x] discuss current justice.gov/foia.gov branding with OIP: How should we handle integration in the near term? Anything we should be aware of re: DOJ branding?

**Comment by ba66e77** [comment] 2017-08-02 15:57
For this research, what are you starting from as a baseline; is the initial starting point the Drupal admin interface that's currently set up or something else?

**Comment by AvivaOskow** [comment] 2017-08-02 16:56
(See #124 also)

I am currently looking into implementing the US Web Design Standards as the basis for our visual style, while maybe attempting to retain some visual connection to the existing foia.gov. The benefit of this approach would be that if redesigning the rest of foia.gov is indeed out of scope, the standards can be more easily used to continue that work after the engagement.

Also for now, we are moving forward with creating a unified design style that works for both the requester and agency side of the product. Implementing this for both sides is the best case scenario, and although we heard yesterday that may be out of scope for the agency side, we want to have it ready to go as part of what 18F committed to delivering.

**Closed as completed** 2017-08-03 21:03 UTC

**Comment by adborden** [comment] 2017-08-03 23:16
Just closing the loop here, we think this is a dupe of  https://github.com/18f/foia-recommendations/issues/124, so feel free to follow up there.
