### ISSUE TITLE
Create Google form for agency info updater

### ISSUE THREAD

**Issue by vz3** [usdoj/foia.gov#64] opened 2017-08-15 21:10 UTC
As an agency, in order to update my agency's portal information, I need to be able to update my information on a web-based UI.

Create Google form for agency info updater based upon document in #48
https://docs.google.com/spreadsheets/d/1wmzvMFwensrp82gesFqSwP74Q4FwzYnFw0fDewVZ-dg/edit#gid=0

This issue is split off from #48 

## Acceptance criteria

- [ ] Contents of document are represented in Google form
- [ ] Determine next steps for usability testing.

**Comment by adborden** [comment] 2017-08-18 17:28
Is this a dupe of https://github.com/18F/foia/issues/66 ?

**Comment by RyanSibley** [comment] 2017-08-30 15:36
@adborden I'm not sure if it's a dupe. But there certainly is confusion. The work in the spreadsheet above is to gather contact info FOIA offices/officers. I'm not sure we want a google form to test that -- if so we don't have one yet. Issue #37 exists to build a mockup of what this contact updater will look like. I think @vz3 has opinions on whether he'd like to use that mock up for content testing--I'd be OK with that as long as I'm involved in the testing. We do have a google form to test the info referenced in #66 which is to collect fields to facilitate a perfected FOIA request.

**Closed as completed** 2017-09-14 18:43 UTC
