### ISSUE TITLE
Implement Agency Info Updater in Drupal

### ISSUE THREAD

**Issue by pkarman** [usdoj/foia.gov#17] opened 2017-07-20 20:33 UTC
There are some [categories](https://github.com/18F/foia-recommendations/blob/master/schemas.md#what-information-is-in-the-metadata-file) of data within a single component. The UI should reflect that categorization, to help ease the user's orientation to such a big space.

**Comment by ba66e77** [comment] 2017-07-25 12:12
The screenshots below show the FOIA Office content type editing form as it exists at present.  Fields which appear repeated are only to show continuity across the images.

This is using Drupal's default administration theme with some configured field groups.  Basic look and feel like order of form elements, grouping or ungrouping elements, controlling size of text fields, or removing elements from the admin form can be managed by configuration options through the UI.  If we need to get fancier, we'll have to evaluate those needs as they come up.

![edit_foia_office_capto_neque_sudo_tum___foia_gov](https://user-images.githubusercontent.com/1698983/28571286-2fc8069c-7110-11e7-94b1-e35f9347209c.png)
![edit_foia_office_capto_neque_sudo_tum___foia_gov 2](https://user-images.githubusercontent.com/1698983/28571288-32b4fb12-7110-11e7-9ab6-559d4fdfc0a5.png)
![edit_foia_office_capto_neque_sudo_tum___foia_gov 3](https://user-images.githubusercontent.com/1698983/28571289-364fb1a4-7110-11e7-9835-ae1df981d76d.png)
![edit_foia_office_capto_neque_sudo_tum___foia_gov 4](https://user-images.githubusercontent.com/1698983/28571291-3a8ccc84-7110-11e7-8952-5b41879094a8.png)
![edit_foia_office_capto_neque_sudo_tum___foia_gov 5](https://user-images.githubusercontent.com/1698983/28571294-3e15edc2-7110-11e7-8ff5-a1e15184e97b.png)

**Comment by vz3** [comment] 2017-07-31 18:10
Outstanding questions:
- Will this be a GUI?
- How will agencies get to this tool?
- Will it require a login? (If so, how? Does design need to design that interface?)
- What information needs to be edited/submitted?
- Is the FOIA request form included in this story?

**Comment by pkarman** [comment] 2017-07-31 19:37
> Will this be a GUI?

Yes, that was our recommendation via discovery.

> How will agencies get to this tool?

Email them a link and explanation?

> Will it require a login? (If so, how? Does design need to design that interface?)

Yes, see #20 

> What information needs to be edited/submitted?

See #16 

> Is the FOIA request form included in this story?

Yes, see #16

**Comment by adborden** [comment] 2017-08-18 17:10
@malikkotob is this done? This issue isn't really defined. https://github.com/18F/foia/issues/69 covers implementation of the styles, so there would be some other issue to capture integrating that into the Drupal theme.

**Comment by adborden** [comment] 2017-08-30 19:40
Spoke to @malikkotob it sounds like this work is essentially covered by #41.

Duplicate of #41

**Closed as completed by adborden** 2017-08-30 19:40 UTC
